### ISSUE TITLE
[Bug] Grid does not stack when you set a breakpoint size, it should stack (width 100%) below it.

### ISSUE THREAD

**Issue by hanoii** [bootstrap-styled/v4#74]
I was trying bootstrap-styled, at first for a simple grid responsible approach, doesn't seem to be working right out of the box.

I am not using BootstrapProvider but rather including the individual components, it's just a simple attempt: 

```
<Row>
<Col md="6" />
<Col md="6"/>
<Row>
```

Then looking at https://bootstrap-styled.github.io/v4/#/UI%20Components/Row I see it's not working there either.

**Comment by kopax** [comment]
Thanks for choosing bootstrap-styled. We use `<Row />` and `<Col />` without issues within multiple projects.

I have fixed a bug where `xs=12` is now required if you don't want auto col for mobile.

It seems that our documentation and even codesandbox.io : https://codesandbox.io/s/7y732m2q2q 

Is not generating the css for our `.row` class, this is a bug, we are currently looking how to fix it. 

May I know what structure are you trying to achieve ? You may need `<Container />` or `<Container fluid />` or use `noGutters` prop. 

If you believe we are not respecting bootstrap v4, a sample of what you want in bare bootstrap would also help us investigate the css.

/cc @santaclauze

**Comment by kopax** [comment]
Documentation as been fixed during deployment, you can check again: https://bootstrap-styled.github.io/v4/#/UI%20Components/Row

**Comment by hanoii** [comment]
@kopax thanks, and how odd, but this is still not working for me. I can see the styles now on the row, so that's fixed, but something changed for col. I don't quite get the issue from the css as I see the width 50% and the flex wrap/settings on the row/column but I am a col-md-6 as per the example above and I see it stacked above breakpoint or horizontal below breakpoint (the other way around).

<img width="2206" alt="screen shot 2019-01-31 at 10 50 59" src="https://user-images.githubusercontent.com/677879/52058533-6a210c80-2546-11e9-8cde-4f03f15908eb.png">
<img width="1735" alt="screen shot 2019-01-31 at 10 53 02" src="https://user-images.githubusercontent.com/677879/52058540-6ee5c080-2546-11e9-9c67-eaf88ef8826f.png">

**Comment by hanoii** [comment]
```
# npm ls @bootstrap-styled/v4
gatsby-starter-default@1.0.0 /Users/ariel/Sites/confcats/gatsbyhub-conferencedemo
└── @bootstrap-styled/v4@2.0.20 
```

On codesandox it seems to do the same:

https://n03yq9qzqm.codesandbox.io/
https://codesandbox.io/s/n03yq9qzqm

**Comment by kopax** [comment]
I have added to our documentation live preview and it work fine.

```jsx
<Row>
   <Col md="6">asdf1</Col>
   <Col md="6">asdf2</Col>
</Row>
``` 

I have set the `@bootstrap-styled/v4` version in your codesandbox to 2.0.20 and it work fine: https://codesandbox.io/s/nr16mnzo3p

It also seems that codesandbox is dealing bad with styled generate classename, editing force us to reload the page. 

My opinion is that it is fixed, can I have a screenshot of your `/conferencedemo` UI ? 

It seems weird that you have 2.0.20 locally and still have this issue.

Also, can you open your react-debugger tool and do a screenshot like this one:

![image](https://user-images.githubusercontent.com/1866564/52074897-8613c500-25bd-11e9-9e0f-111b918e1129.png)

**Comment by hanoii** [comment]
@kopax I am truly confused, you say it works fine, but for me it doesn't.

See your codesandbox: https://codesandbox.io/s/nr16mnzo3p
And have a look at this one, which is basically plain old bootstrap: https://codesandbox.io/s/3vxo9964l6

It's not the same. On yours, the columns are stacked (on on top of the other) when the browser window is wide and side by side when it's narrow.
On the bootstrap one, is the other way around.

**Comment by kopax** [comment]
@hanoii, thanks a lot for this example, I can now see the issue.

The `.row` and `.col` class have correct css, but there is a dependency with the following rules:

```css
*, ::after, ::before {
    box-sizing: border-box;
}
```

After this being added, then it work exactly the same. This rules is global so it is included within the Bootstrap-Provider. 

We want to support v4 without the need of having @bootstrap-styled/provider for quick prototyping and code sharing. This needs to be fixed.

I will add the following rules to `<Row />` component so it can fix your issue. I will update asap.

I don't know the full list that also depends on that rule but since you are testing v4 without a `<BootstrapProvider />`, I think all your feedback will be very usefull, feel free to open more issue when you hit such unexpected behavior.

Fix is in progress.

**Comment by kopax** [comment]
/cc @hanoii I have updated the version on my codesandbox so you can see the fix working: https://codesandbox.io/s/nr16mnzo3p 

The generated css on `.col` now have the additional rule:

```css
.iUVxfs.row *, .iUVxfs.row ::after, .iUVxfs.row ::before {
    box-sizing: border-box;
}
```

**Comment by hanoii** [comment]
@kopax sorry to be such a pain, but it's not quite there yet. If you look at your codesandbox, now it probably displays side by side above md breakpoint, but also below md. below md it should stack.

**Comment by kopax** [comment]
@hanoii bootstrap 3 is different than bootstrap 4.

What you are describing is bootstrap 3 behavior.

Quoting bs 4 documentation:

> Thanks to flexbox, grid columns without a specified width will automatically layout as equal width columns. For example, four instances of .col-sm will each automatically be 25% wide from the small breakpoint and up. See the auto-layout columns section for more examples.

Source: https://getbootstrap.com/docs/4.1/layout/grid

This is an updated codesandbox of what you are trying to achieve: https://codesandbox.io/s/my596x0knx

If this is still not respecting bootstrap 4 specification, please provide another example with the difference between both.

**Comment by hanoii** [comment]
The quote refers at something else, not wether something stacks or no. You are not forced to specify full with of all sizes. Once you set a breakpoint size, it will stack (width 100%) below it.

You can compare yours to the one I sent above https://codesandbox.io/s/3vxo9964l6. I just added more examples, but you'll see it will stack regardless if setting a size for xs. I added one for lg as well.

That's bootstrap 4.

**Comment by kopax** [comment]
Interesting, I've been using bootstrap 3 for a while and when I saw that bug and found that quotation, I thought everything was good.

Looking at your codesandbox, I can see the difference. 

I have made this codesandbox as a BS equivalent: https://codesandbox.io/s/my596x0knx

**Comment by santaclauze** [comment]
@kopax, I think that if we start implementing props as className we will create confusion with other components and what props can activate what className.

I think we should opt for `<Col className="col" />`.

**Comment by kopax** [comment]
@hanoii we with @santaclauze agreed that adding other props that would create confusion will be less direct than simply using `className` as usual which is what we decided to used also for utilities from `<BootstrapProvider />`.

I agree with you for `col-6`, as this is also new. Perhaps adding a `col` props that is having the same behavor as `xs|sm|md|lg` would solve the issue.

That will add the explanation that we decided to remove the prefix `col-` to `xs|sm|md|lg` to reduce repetition. 

/cc @santaclauze @hanoii

**Comment by kopax** [comment]
Hi @hanoii, yes we will took that option, I am releasing a fix now.

- `<Col />` will render `.col`
- `<Col xs />` is bad synthax
- `<Col sm />` is already rendering `.col-sm`

To add `col-6`, you can do : 

- `<Col xs={6} />` is already rendering `.col-6`

I am releasing a fix now.

**Comment by kopax** [comment]
I am closing this.

Could you please have a quick look and test again @hanoii  ? : https://codesandbox.io/s/my596x0knx

**Comment by hanoii** [comment]
seems to work now, thanks @kopax !!!

Side question: how did you handle this project. Did you manually moved all rules into its SC equivalent or you have better logic in to keep their CSS? I am mostly worried of the upgradability of this library. Each bootstrap fix needs a manual update on this library?

**Comment by hanoii** [comment]
@kopax sorry for the poorly written question.

but you did answer it. So each change or bugfix on bootstrap needs to manually be carried over, correct?

**Comment by kopax** [comment]
Yes, it needs to be manually update and I don't see any other option. We will respect v4 specification and will take feedback as this one to keep up to date our lib with the group feedback.
